import {
  PeripheralItem,
  InternalComponent,
  ComputerCategory,
  AssemblyStep,
  QuizQuestion,
  GlossaryItem,
} from '../types/hardware';

export const TRIO_CONCEPTS = [
  {
    id: 'hardware',
    title: 'Hardware',
    subtitle: 'A Parte Física (O que você pode tocar)',
    analogy: 'É como o Corpo Humano (ossos, mãos, olhos e coração)',
    popularJoke: 'É a parte que você chuta quando o computador trava!',
    description:
      'São todas as peças de metal, plástico, placas e fios que formam o computador. Sem o hardware, o computador não existe fisicamente.',
    examples: ['Teclado', 'Mouse', 'Monitor', 'Placa de circuitos', 'Fios de energia'],
    color: 'amber',
    badge: 'Físico / Tangível',
    theme: {
      bg: 'bg-amber-50',
      border: 'border-amber-300',
      text: 'text-amber-900',
      accent: 'bg-amber-500 text-white',
      ring: 'ring-amber-400',
    },
  },
  {
    id: 'software',
    title: 'Software',
    subtitle: 'A Parte Lógica (Os programas e ideias)',
    analogy: 'É como a Mente e os Pensamentos (ou uma receita de bolo)',
    popularJoke: 'É a parte que você xinga quando algo não funciona!',
    description:
      'São as instruções invisíveis, os programas, os aplicativos do celular, os jogos e o Windows. Eles dizem ao hardware exatamente o que fazer.',
    examples: ['WhatsApp', 'Navegador de Internet', 'Jogos', 'Windows', 'Calculadora'],
    color: 'emerald',
    badge: 'Lógico / Digital',
    theme: {
      bg: 'bg-emerald-50',
      border: 'border-emerald-300',
      text: 'text-emerald-900',
      accent: 'bg-emerald-600 text-white',
      ring: 'ring-emerald-400',
    },
  },
  {
    id: 'peopleware',
    title: 'Peopleware',
    subtitle: 'As Pessoas (O usuário e quem cria)',
    analogy: 'É o Motorista do carro ou o Cozinheiro que faz a receita',
    popularJoke: 'É a pessoa que comemora quando tudo dá certo!',
    description:
      'São os seres humanos que usam, programam, montam e cuidam dos computadores. Sem as pessoas, o computador não tem utilidade.',
    examples: ['Você usando o PC', 'Digitador', 'Programador', 'Técnico de informática'],
    color: 'indigo',
    badge: 'Humano / Usuário',
    theme: {
      bg: 'bg-indigo-50',
      border: 'border-indigo-300',
      text: 'text-indigo-900',
      accent: 'bg-indigo-600 text-white',
      ring: 'ring-indigo-400',
    },
  },
];

export const INTERNAL_COMPONENTS: InternalComponent[] = [
  {
    id: 'motherboard',
    name: 'Placa-Mãe (Motherboard)',
    nickname: 'A Grande Cidade Conectada',
    iconName: 'Cpu',
    bodyAnalogy: 'O Esqueleto e Sistema Nervoso',
    cityAnalogy: 'As Avenidas e Rodovias da cidade por onde todos transitam',
    summary: 'A placa principal onde todas as outras peças são encaixadas e conversam entre si.',
    detail:
      'Ela possui trilhas elétricas que transmitem informações em alta velocidade entre o cérebro (processador), a memória e as placas de vídeo.',
    whatHappensWithoutIt: 'Nenhuma peça conseguiria conversar com a outra; o computador vira um monte de peças soltas.',
    color: 'emerald',
    bgLight: 'bg-emerald-50 text-emerald-900',
    borderCol: 'border-emerald-300',
    locationInCase: 'Fixada no fundo do gabinete com parafusos e espaçadores.',
  },
  {
    id: 'cpu',
    name: 'Processador (CPU)',
    nickname: 'O Cérebro Pensante',
    iconName: 'Activity',
    bodyAnalogy: 'O Cérebro Humano',
    cityAnalogy: 'A Prefeitura e o Engenheiro Chefe que tomam todas as decisões',
    summary: 'Faz bilhões de cálculos por segundo e executa todas as ordens dos programas.',
    detail:
      'Tudo o que você clica ou digita passa por ele. Ele esquenta bastante enquanto pensa, por isso precisa de um ventilador (cooler) em cima dele.',
    whatHappensWithoutIt: 'O computador não liga e não toma nenhuma decisão lógica.',
    color: 'blue',
    bgLight: 'bg-blue-50 text-blue-900',
    borderCol: 'border-blue-300',
    locationInCase: 'Encaixado no soquete central protegido no meio da Placa-Mãe.',
  },
  {
    id: 'ram',
    name: 'Memória RAM',
    nickname: 'A Mesa de Trabalho Rápida',
    iconName: 'Layers',
    bodyAnalogy: 'A Memória de Curto Prazo',
    cityAnalogy: 'A bancada do atendente onde ficam os papéis do momento',
    summary: 'Guarda as informações dos aplicativos abertos no exato momento em que você está usando.',
    detail:
      'Quanto mais memória RAM, mais abas de internet e aplicativos você consegue abrir ao mesmo tempo sem travar. Quando desliga o PC, ela se apaga completamente.',
    whatHappensWithoutIt: 'O computador fica extremamente lento ou nem sequer inicia.',
    color: 'purple',
    bgLight: 'bg-purple-50 text-purple-900',
    borderCol: 'border-purple-300',
    locationInCase: 'Pentes compridos encaixados nos slots verticais ao lado da CPU.',
  },
  {
    id: 'storage',
    name: 'Armazenamento (SSD / HD)',
    nickname: 'O Grande Armário de Arquivos',
    iconName: 'HardDrive',
    bodyAnalogy: 'A Memória de Longo Prazo',
    cityAnalogy: 'A Biblioteca e o Cartório onde tudo fica guardado para sempre',
    summary: 'Guarda suas fotos, músicas, vídeos e o Windows mesmo depois de desligar o PC.',
    detail:
      'O SSD moderno é até 10 vezes mais rápido que o antigo HD de disco mecânico, fazendo o computador ligar em poucos segundos.',
    whatHappensWithoutIt: 'Você não tem onde salvar nenhum arquivo nem instalar o Windows.',
    color: 'amber',
    bgLight: 'bg-amber-50 text-amber-900',
    borderCol: 'border-amber-300',
    locationInCase: 'Encaixado direto na placa-mãe (SSD M.2) ou em gavetas do gabinete.',
  },
  {
    id: 'psu',
    name: 'Fonte de Alimentação',
    nickname: 'O Coração de Energia',
    iconName: 'Zap',
    bodyAnalogy: 'O Coração que Bombeia Sangue',
    cityAnalogy: 'A Usina Elétrica que alimenta todas as casas com voltagem certa',
    summary: 'Recebe a energia da tomada (110V/220V) e transforma em voltagens seguras (12V, 5V, 3.3V).',
    detail:
      'Ela envia cabos de energia coloridos para a placa-mãe, placa de vídeo e discos. Uma fonte de boa qualidade protege o PC contra queimas e raios.',
    whatHappensWithoutIt: 'Nada recebe energia elétrica e nada funciona.',
    color: 'rose',
    bgLight: 'bg-rose-50 text-rose-900',
    borderCol: 'border-rose-300',
    locationInCase: 'Geralmente na parte inferior traseira do gabinete.',
  },
  {
    id: 'gpu',
    name: 'Placa de Vídeo (GPU)',
    nickname: 'O Artista Visual',
    iconName: 'Monitor',
    bodyAnalogy: 'Os Olhos e as Mãos do Pintor',
    cityAnalogy: 'O Cinema e o Telão de Alta Definição da cidade',
    summary: 'Desenha na tela do monitor todas as imagens, vídeos, cores e gráficos dos jogos.',
    detail:
      'Muitos processadores já vêm com vídeo integrado básico para escritório. Já para jogos pesados ou edição 3D, usamos uma placa de vídeo dedicada forte.',
    whatHappensWithoutIt: 'Sem vídeo integrado ou placa dedicada, o monitor fica com a tela preta.',
    color: 'teal',
    bgLight: 'bg-teal-50 text-teal-900',
    borderCol: 'border-teal-300',
    locationInCase: 'Encaixada no slot PCIe horizontal mais longo da placa-mãe.',
  },
  {
    id: 'cooler',
    name: 'Cooler e Ventoinhas',
    nickname: 'O Ar-Condicionado',
    iconName: 'Wind',
    bodyAnalogy: 'O Suor e a Respiração que Resfriam o Corpo',
    cityAnalogy: 'O Sistema de Ventilação que evita o superaquecimento',
    summary: 'Assopra ar fresco e retira o calor gerado pelas peças para que não queimem.',
    detail:
      'O processador gera muito calor quando trabalha. O cooler de metal absorve esse calor e a ventoinha sopra para fora do gabinete.',
    whatHappensWithoutIt: 'O computador desliga sozinho por segurança após 2 minutos para não derreter.',
    color: 'cyan',
    bgLight: 'bg-cyan-50 text-cyan-900',
    borderCol: 'border-cyan-300',
    locationInCase: 'Em cima do processador e nas grades da frente e de trás do gabinete.',
  },
  {
    id: 'case',
    name: 'Gabinete (Chassi)',
    nickname: 'A Casa Protetora',
    iconName: 'Box',
    bodyAnalogy: 'A Pele e a Caixa Torácica',
    cityAnalogy: 'Os Muros e a Estrutura do Prédio',
    summary: 'A caixa de metal e vidro que acomoda e protege todas as peças com segurança.',
    detail:
      'Possui botões para ligar, entradas USB frontais e passagens especiais para organizar os fios sem bagunça.',
    whatHappensWithoutIt: 'As peças ficariam soltas na mesa, expostas a poeira, líquidos e riscos de curto.',
    color: 'slate',
    bgLight: 'bg-slate-100 text-slate-900',
    borderCol: 'border-slate-300',
    locationInCase: 'É a própria estrutura externa do computador.',
  },
];

export const PERIPHERALS: PeripheralItem[] = [
  // ENTRADA
  {
    id: 'teclado',
    name: 'Teclado',
    type: 'entrada',
    typeLabel: 'Periférico de Entrada',
    emoji: '⌨️',
    simpleAnalogy: 'Como a Caneta que escreve',
    description: 'Envia letras, números e comandos com seus dedos para dentro do computador.',
    howItWorks: 'Você aperta a tecla → O computador recebe o sinal elétrico e mostra a letra na tela.',
    color: 'blue',
    bgLight: 'bg-blue-50',
    borderCol: 'border-blue-300',
    tags: ['Digitação', 'Comandos', 'Atalhos'],
  },
  {
    id: 'mouse',
    name: 'Mouse (Rato)',
    type: 'entrada',
    typeLabel: 'Periférico de Entrada',
    emoji: '🖱️',
    simpleAnalogy: 'Como o seu Dedo Indicador',
    description: 'Move a setinha na tela e clica nas coisas que você deseja abrir ou selecionar.',
    howItWorks: 'O sensor de luz embaixo lê o movimento da sua mão e move a seta com precisão.',
    color: 'blue',
    bgLight: 'bg-blue-50',
    borderCol: 'border-blue-300',
    tags: ['Apontar', 'Clicar', 'Arrastar'],
  },
  {
    id: 'microfone',
    name: 'Microfone',
    type: 'entrada',
    typeLabel: 'Periférico de Entrada',
    emoji: '🎙️',
    simpleAnalogy: 'Como a sua Voz e Ouvido do PC',
    description: 'Captura o som da sua fala para chamadas de vídeo, áudios e comandos de voz.',
    howItWorks: 'Sua voz vibra o ar → O microfone transforma o som em ondas digitais que o PC entende.',
    color: 'blue',
    bgLight: 'bg-blue-50',
    borderCol: 'border-blue-300',
    tags: ['Áudio', 'Chamadas', 'Voz'],
  },
  {
    id: 'webcam',
    name: 'Câmera / Webcam',
    type: 'entrada',
    typeLabel: 'Periférico de Entrada',
    emoji: '📷',
    simpleAnalogy: 'Como o Olho do Computador',
    description: 'Grava seu rosto e ambiente para reuniões do Zoom, WhatsApp e fotos.',
    howItWorks: 'A lente captura a luz e transmite imagens em movimento diretamente para o sistema.',
    color: 'blue',
    bgLight: 'bg-blue-50',
    borderCol: 'border-blue-300',
    tags: ['Vídeo', 'Reuniões', 'Fotos'],
  },
  {
    id: 'scanner',
    name: 'Scanner / Leitor',
    type: 'entrada',
    typeLabel: 'Periférico de Entrada',
    emoji: '📄',
    simpleAnalogy: 'Como uma Fotocopiadora Digital',
    description: 'Lê uma folha de papel física e a transforma em uma foto dentro do computador.',
    howItWorks: 'Passa uma lâmpada brilhante sobre o documento e digitaliza o texto e as fotos.',
    color: 'blue',
    bgLight: 'bg-blue-50',
    borderCol: 'border-blue-300',
    tags: ['Documentos', 'Boletos', 'Fotos Antigas'],
  },

  // SAÍDA
  {
    id: 'monitor',
    name: 'Monitor (Tela)',
    type: 'saida',
    typeLabel: 'Periférico de Saída',
    emoji: '🖥️',
    simpleAnalogy: 'Como a Janela onde você vê tudo',
    description: 'Mostra visualmente tudo o que o computador está fazendo em forma de imagens e textos.',
    howItWorks: 'Recebe os pontos de luz (pixels) da placa de vídeo e acende milhões de cores.',
    color: 'amber',
    bgLight: 'bg-amber-50',
    borderCol: 'border-amber-300',
    tags: ['Visão', 'Cores', 'Vídeos'],
  },
  {
    id: 'caixa-som',
    name: 'Caixas de Som',
    type: 'saida',
    typeLabel: 'Periférico de Saída',
    emoji: '🔊',
    simpleAnalogy: 'Como a Boca que fala com você',
    description: 'Toca as músicas, vozes de vídeos e alertas sonoros do computador para a sala inteira ouvir.',
    howItWorks: 'Converte a informação de áudio digital em vibrações físicas no ar que seu ouvido escuta.',
    color: 'amber',
    bgLight: 'bg-amber-50',
    borderCol: 'border-amber-300',
    tags: ['Músicas', 'Filmes', 'Alertas'],
  },
  {
    id: 'fone-ouvido',
    name: 'Fones de Ouvido',
    type: 'saida',
    typeLabel: 'Periférico de Saída',
    emoji: '🎧',
    simpleAnalogy: 'Como um Sussurro particular no seu ouvido',
    description: 'Permite ouvir o som com privacidade total sem incomodar as pessoas ao redor.',
    howItWorks: 'Pequenos alto-falantes colocados dentro ou sobre suas orelhas transmitem o som com fidelidade.',
    color: 'amber',
    bgLight: 'bg-amber-50',
    borderCol: 'border-amber-300',
    tags: ['Privacidade', 'Música', 'Estudo'],
  },
  {
    id: 'impressora',
    name: 'Impressora Tradicional',
    type: 'saida',
    typeLabel: 'Periférico de Saída',
    emoji: '🖨️',
    simpleAnalogy: 'O Carimbo que passa para o Papel',
    description: 'Pega textos e fotos que estão na tela e os imprime com tinta em folhas de papel reais.',
    howItWorks: 'Recebe o arquivo do PC e injeta microgotas de tinta com precisão na folha branca.',
    color: 'amber',
    bgLight: 'bg-amber-50',
    borderCol: 'border-amber-300',
    tags: ['Papel', 'Trabalhos', 'Contratos'],
  },

  // MISTOS (ENTRADA E SAÍDA)
  {
    id: 'touchscreen',
    name: 'Tela Sensível ao Toque (Touch)',
    type: 'misto',
    typeLabel: 'Periférico Misto (Entrada e Saída)',
    emoji: '📱',
    simpleAnalogy: 'Tela que você vê E aperta com os dedos',
    description: 'Ao mesmo tempo mostra as imagens (Saída) e aceita o toque dos seus dedos como cliques (Entrada).',
    howItWorks: 'Une uma tela de exibição com uma camada elétrica invisível que detecta o toque da pele.',
    color: 'emerald',
    bgLight: 'bg-emerald-50',
    borderCol: 'border-emerald-300',
    tags: ['Celulares', 'Tablets', 'Caixas de Banco'],
  },
  {
    id: 'pendrive',
    name: 'Pendrive / HD Externo',
    type: 'misto',
    typeLabel: 'Periférico Misto (Entrada e Saída)',
    emoji: '💾',
    simpleAnalogy: 'Mochila que leva e traz arquivos',
    description: 'Você pode tanto salvar arquivos nele (Saída) quanto abrir fotos dele no PC (Entrada).',
    howItWorks: 'Memória flash portátil conectada via porta USB com leitura e gravação bidirecional.',
    color: 'emerald',
    bgLight: 'bg-emerald-50',
    borderCol: 'border-emerald-300',
    tags: ['Transporte', 'Backup', 'Fotos'],
  },
  {
    id: 'headset',
    name: 'Headset (Fone + Microfone)',
    type: 'misto',
    typeLabel: 'Periférico Misto (Entrada e Saída)',
    emoji: '🎙️🎧',
    simpleAnalogy: 'Telefone completo na cabeça',
    description: 'Possui fone para você escutar os outros (Saída) e haste de microfone para você falar (Entrada).',
    howItWorks: 'Dois canais no mesmo cabo: um canal envia sua voz ao PC e outro canal traz o áudio até seu ouvido.',
    color: 'emerald',
    bgLight: 'bg-emerald-50',
    borderCol: 'border-emerald-300',
    tags: ['Atendimento', 'Jogos Online', 'Aulas'],
  },
];

export const COMPUTER_CATEGORIES: ComputerCategory[] = [
  {
    id: 'computador-basico',
    title: '1. Computador Básico / Estudos & Escritório',
    tagline: 'Ideal para tarefas simples do dia a dia, aulas e internet',
    audience: 'Estudantes, aposentados, pequenas empresas e tarefas domésticas.',
    priceRange: 'R$ 1.200 a R$ 1.900',
    powerConsumption: 'Baixíssimo (~40W a 65W na tomada)',
    specsSummary: [
      'Processador: Intel Celeron / Core i3 ou AMD Ryzen 3',
      'Memória RAM: 8 GB DDR4 (suficiente para multitarefas leves)',
      'Armazenamento: SSD de 256 GB ou 512 GB (inicia rápido)',
      'Vídeo: Integrado na própria CPU (sem placa separada)',
      'Formato: Mini PC compacto ou Desktop torre tradicional',
    ],
    pros: [
      'Preço acessível e baixo consumo de energia',
      'Silencioso e ocupa pouco espaço',
      'Perfeito para navegar na web, YouTube, Word e Excel',
    ],
    officialSource: {
      name: 'FGVcia - Pesquisa Anual do Uso de TI no Brasil & TIC Domicílios',
      description: 'Levantamento oficial de indicadores de inclusão digital e varejo eletrônico nacional.',
      year: '2024/2025',
    },
    recommendedFor: 'Digitação, ver vídeos no YouTube, ler notícias, pesquisas escolares e videochamadas no WhatsApp.',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    accentColor: 'emerald',
  },
  {
    id: 'computador-intermediario',
    title: '2. Computador Intermediário / Notebook Portátil',
    tagline: 'Equilíbrio perfeito de velocidade e mobilidade para trabalhar',
    audience: 'Universitários, profissionais de home office e quem precisa levar na mochila.',
    priceRange: 'R$ 2.400 a R$ 3.900',
    powerConsumption: 'Muito baixo (~45W a 65W com bateria integrada)',
    specsSummary: [
      'Processador: Intel Core i5 ou AMD Ryzen 5 (6 a 10 núcleos)',
      'Memória RAM: 8 GB a 16 GB DDR4/DDR5',
      'Armazenamento: SSD NVMe ultrarrápido de 512 GB',
      'Tela: 15.6 polegadas Full HD com teclado numérico',
      'Bateria: 4 a 7 horas longe da tomada',
    ],
    pros: [
      'Leva para qualquer lugar com facilidade',
      'Abre dezenas de abas e programas simultâneos sem engasgar',
      'Já vem com tela, teclado, webcam e microfone integrados',
    ],
    officialSource: {
      name: 'IDC Brasil PC Tracker & Cetic.br / NIC.br',
      description: 'Dados consolidados de vendas de computadores pessoais no Brasil.',
      year: '2024/2025',
    },
    recommendedFor: 'Trabalho de escritório, planilhas pesadas, aulas da faculdade, apresentações e viagens.',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-300',
    accentColor: 'blue',
  },
  {
    id: 'computador-gamer',
    title: '3. Computador de Alto Desempenho / Gamer & 3D',
    tagline: 'Poder máximo para jogos modernos, engenharia e edição de vídeo',
    audience: 'Gamers exigentes, arquitetos (AutoCAD/3D), editores de cinema e programadores.',
    priceRange: 'R$ 5.500 a R$ 9.800+',
    powerConsumption: 'Médio a Alto (~300W a 600W sob carga pesada)',
    specsSummary: [
      'Processador: Intel Core i7 / i9 ou AMD Ryzen 7 / 9',
      'Placa de Vídeo Dedicada: Nvidia GeForce RTX 4060 / 4070 ou Radeon RX',
      'Memória RAM: 16 GB a 32 GB DDR5 de alta velocidade',
      'Armazenamento: SSD NVMe de 1 TB a 2 TB',
      'Refrigeração: Water Cooler líquido ou dissipador duplo',
    ],
    pros: [
      'Gráficos realistas e altíssima taxa de quadros (FPS)',
      'Renderiza vídeos 4K e maquetes 3D em tempo recorde',
      'Facilidade total para trocar peças no futuro (upgrade)',
    ],
    officialSource: {
      name: 'Levantamento de Mercado E-commerce & Pesquisas de Hardware Brasil',
      description: 'Média de preços dos principais distribuidores e varejistas especializados.',
      year: '2024/2025',
    },
    recommendedFor: 'Jogos de última geração, edição profissional de vídeo 4K, modelagem 3D, projetos de engenharia e IA local.',
    badgeColor: 'bg-purple-100 text-purple-800 border-purple-300',
    accentColor: 'purple',
  },
];

export const STATIC_ELECTRICITY_RULES = [
  {
    icon: '⚡',
    title: 'O que é a Eletricidade Estática (ESD)?',
    desc: 'É aquela pequena carga elétrica que se acumula no nosso corpo quando andamos em carpetes ou usamos blusas de lã. Para nós é só um choquezinho bobo, mas para os chips microscópicos é como um raio devastador!',
  },
  {
    icon: '🛡️',
    title: 'Regra 1: Descarregue seu corpo antes de tocar nas peças',
    desc: 'Toque com as duas mãos em um objeto de metal sem pintura (como uma torneira ou a parte metálica do gabinete desconectado) por 5 segundos para zerar a estática.',
  },
  {
    icon: '🪑',
    title: 'Regra 2: Bancada limpa, firme e sem tecidos',
    desc: 'Monte sempre sobre uma mesa de madeira lisa e seca. NUNCA monte o computador em cima de cama, colchão, sofá ou tapete felpudo!',
  },
  {
    icon: '🖐️',
    title: 'Regra 3: Segure as peças sempre pelas bordas',
    desc: 'Nunca passe os dedos sobre os pinos dourados de contato da memória ou do processador. A oleosidade natural da pele e a estática podem estragá-los.',
  },
  {
    icon: '🔌',
    title: 'Regra 4: Desconecte tudo da tomada',
    desc: 'Jamais mexa em peças internas com o cabo da fonte ligado na tomada elétrica da parede. Segurança sua e do equipamento em primeiro lugar!',
  },
  {
    icon: '📦',
    title: 'Regra 5: Guarde parafusos em potinhos separados',
    desc: 'Os parafusos da placa-mãe, da fonte e do gabinete têm roscas diferentes. Usar o parafuso errado pode quebrar a rosca metálica.',
  },
];

export const ASSEMBLY_STEPS: AssemblyStep[] = [
  {
    stepNumber: 1,
    title: 'Passo 1: Preparar a Bancada e a Placa-Mãe',
    shortTitle: 'Preparar a Bancada',
    icon: 'Layers',
    goal: 'Montar os componentes principais com a placa-mãe apoiada sobre a própria caixa de papelão, fora do gabinete.',
    safetyCaution: 'Nunca apoie a placa-mãe em cima do saco plástico antiestático cinza por fora, pois o lado externo pode conduzir eletricidade. Apoie na caixa de papelão.',
    stepByStepActions: [
      'Limpe a mesa e lave as mãos secando bem.',
      'Abra a caixa da placa-mãe e coloque-a sobre a tampa de papelão.',
      'Separe a chave philips imantada e potinhos para parafusos.',
    ],
    antiStaticTip: 'Toque na torneira de metal ou na estrutura descarregada antes de abrir a caixa.',
    proTip: 'Montar a CPU, cooler e RAM fora do gabinete dá 10x mais espaço para as mãos!',
    color: 'emerald',
  },
  {
    stepNumber: 2,
    title: 'Passo 2: Instalar o Processador (CPU)',
    shortTitle: 'Instalar o Processador',
    icon: 'Cpu',
    goal: 'Encaixar o cérebro no soquete da placa-mãe sem entortar nenhum dos milhares de pinos minúsculos.',
    safetyCaution: 'NUNCA force para baixo! O processador possui o sistema "Gravidade Zero": se estiver na posição certa, ele desliza suavemente para o lugar.',
    stepByStepActions: [
      'Levante a alavanca de metal do soquete da placa-mãe.',
      'Procure o triângulo dourado marcado em um dos cantos do processador.',
      'Alinhe com o triângulo marcado no soquete da placa-mãe.',
      'Solte o processador com delicadeza no encaixe.',
      'Abaixe a alavanca de metal até travar (a tampa plástica de proteção soltará sozinha).',
    ],
    antiStaticTip: 'Pegue o processador apenas pelas bordas laterais, sem encostar embaixo nos pinos ou contatos.',
    proTip: 'Confira duas vezes o triângulo dourado antes de fechar a alavanca.',
    color: 'blue',
  },
  {
    stepNumber: 3,
    title: 'Passo 3: Instalar as Memórias RAM',
    shortTitle: 'Instalar as Memórias RAM',
    icon: 'Layers',
    goal: 'Encaixar os pentes de memória nos trilhos até ouvir o som de travamento ("CLIQUE").',
    safetyCaution: 'A memória tem um corte (chanfro) fora do centro na parte dourada. Ela só entra de um lado. Verifique a posição antes de pressionar.',
    stepByStepActions: [
      'Abra as travinhas plásticas nas pontas dos slots de memória.',
      'Alinhe o rasgo central da memória com o relevo do slot.',
      'Apoie os dois polegares nas extremidades do pente de memória.',
      'Empurre para baixo de forma reta e firme até ouvir o "CLIC" das travas se fecharem sozinhas.',
    ],
    antiStaticTip: 'Não toque nos contatos dourados inferiores.',
    proTip: 'Se sua placa-mãe tem 4 slots e você tem 2 memórias, use os slots 2 e 4 (Dual Channel para o dobro de velocidade).',
    color: 'purple',
  },
  {
    stepNumber: 4,
    title: 'Passo 4: Instalar o Armazenamento SSD M.2 e o Cooler',
    shortTitle: 'SSD M.2 e Cooler',
    icon: 'Wind',
    goal: 'Encaixar o SSD ultrarrápido e fixar o ventilador que vai resfriar o processador.',
    safetyCaution: 'Lembre-se de retirar o plástico transparente adesivo que vem grudado embaixo do cooler antes de colocar sobre a CPU!',
    stepByStepActions: [
      'Insira o SSD M.2 no slot inclinado a 30 graus e aperte o pequeno parafuso de fixação.',
      'Verifique se o cooler já possui pasta térmica cinza pré-aplicada ou pingue uma gota do tamanho de uma ervilha no centro do processador.',
      'Posicione o cooler reto sobre a CPU e aperte os parafusos em padrão de cruz (X) para espalhar a pressão por igual.',
      'Conecte o cabinho do ventilador no conector escrito "CPU_FAN" na placa-mãe.',
    ],
    antiStaticTip: 'Mantenha a bancada estável sem movimentos bruscos.',
    proTip: 'Apertar os parafusos em cruz evita que a pasta térmica escape de um lado só.',
    color: 'cyan',
  },
  {
    stepNumber: 5,
    title: 'Passo 5: Instalar a Fonte de Alimentação no Gabinete',
    shortTitle: 'Instalar a Fonte',
    icon: 'Zap',
    goal: 'Fixar o coração de energia e começar a organizar os cabos com antecedência.',
    safetyCaution: 'Coloque a ventoinha da fonte voltada para a grelha de ventilação (geralmente apontada para o chão do gabinete).',
    stepByStepActions: [
      'Deslize a fonte no compartimento inferior traseiro do gabinete.',
      'Alinhe com a furação traseira e aperte os 4 parafusos sextavados.',
      'Passe os cabos principais (24 pinos e 8 pinos da CPU) pela parte de trás do gabinete para não ficarem soltos no meio do vento.',
    ],
    antiStaticTip: 'A própria carcaça de metal da fonte instalada ajuda a aterrar o gabinete.',
    proTip: 'Use as abraçadeiras plásticas (enforca-gato) para agrupar cabos parecidos.',
    color: 'rose',
  },
  {
    stepNumber: 6,
    title: 'Passo 6: Instalar o Espelho Traseiro e a Placa-Mãe no Gabinete',
    shortTitle: 'Fixar a Placa no Gabinete',
    icon: 'Box',
    goal: 'Acomodar com segurança o conjunto montado dentro da carcaça do gabinete.',
    safetyCaution: 'NUNCA parafuse a placa-mãe direto na chapa de metal crua! Certifique-se de que os suportes espaçadores de latão estão nos lugares certos.',
    stepByStepActions: [
      'Encaixe o espelho traseiro de metal na abertura do gabinete com um clique.',
      'Confira se os parafusos espaçadores dourados estão alinhados com os furos da sua placa-mãe.',
      'Segure a placa-mãe pelo corpo do cooler e deite-a suavemente dentro do gabinete.',
      'Aperte os parafusos da placa-mãe de maneira firme, mas sem arrochar demais para não trincar a fibra.',
    ],
    antiStaticTip: 'Evite raspar a placa nas laterais de metal do gabinete.',
    proTip: 'Coloque primeiro o parafuso central para manter a placa alinhada com as portas traseiras.',
    color: 'amber',
  },
  {
    stepNumber: 7,
    title: 'Passo 7: Conectar Cabos de Energia e Painel Frontal',
    shortTitle: 'Ligar os Cabos e Painel',
    icon: 'Plug',
    goal: 'Dar energia a tudo e conectar os botões de Ligar e as portas USB da frente.',
    safetyCaution: 'Os cabos de força possuem travas com formato específico (quadrados e arredondados). Se não entrar fácil, verifique a orientação.',
    stepByStepActions: [
      'Conecte o cabo grosso de 24 pinos no lado direito da placa-mãe até ouvir o clique.',
      'Conecte o cabo EPS de 8 pinos no canto superior esquerdo (energia da CPU).',
      'Conecte os pequenos fios do painel frontal (Power SW para o botão liga/desliga, Reset, LED de disco) seguindo o manual da placa.',
      'Conecte o cabo do USB frontal e o cabo de áudio frontal (HD Audio).',
    ],
    antiStaticTip: 'Trabalhe com o cabo de energia da parede desconectado.',
    proTip: 'O conector Power SW não tem polaridade de positivo/negativo, funciona em qualquer sentido!',
    color: 'indigo',
  },
  {
    stepNumber: 8,
    title: 'Passo 8: Instalar a Placa de Vídeo e Primeiro Teste',
    shortTitle: 'Placa de Vídeo e Teste',
    icon: 'CheckCircle2',
    goal: 'Encaixar a placa de vídeo dedicada (se tiver), ligar na tomada e ver a tela de boas-vindas!',
    safetyCaution: 'Ligue o cabo de vídeo HDMI ou DisplayPort ATRÁS DA PLACA DE VÍDEO, e não na saída da placa-mãe!',
    stepByStepActions: [
      'Retire as duas tampinhas metálicas de trás do gabinete na linha do slot PCIe.',
      'Abra a trava do slot PCIe e encaixe a Placa de Vídeo até travar.',
      'Aperte os parafusos traseiros de suporte e conecte o cabo de energia PCIe (6+2 pinos da fonte).',
      'Conecte o monitor, teclado e mouse.',
      'Ligue o botão da fonte e aperte o botão POWER na frente. Parabéns, seu computador ganhou vida!',
    ],
    antiStaticTip: 'Feche a tampa lateral de vidro antes de usar no dia a dia.',
    proTip: 'Ao ligar pela primeira vez, aperte repetidamente a tecla DELETE ou F2 para entrar na tela da BIOS e conferir se todas as peças foram reconhecidas.',
    color: 'emerald',
  },
];

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: 'Qual é a diferença mais simples entre Hardware e Software?',
    illustration: '💻🧠',
    category: 'hardware-software',
    options: [
      {
        text: 'Hardware é o corpo físico que você pega na mão; Software são os programas e pensamentos invisíveis.',
        isCorrect: true,
        explanation: 'Perfeito! Hardware é tudo o que tem matéria física (teclado, peças), e software são as instruções e programas (WhatsApp, jogos).',
      },
      {
        text: 'Hardware é a internet e Software é o cabo de energia.',
        isCorrect: false,
        explanation: 'Incorreto. A internet é uma rede de comunicação e o cabo é um hardware físico.',
      },
      {
        text: 'Não existe diferença, os dois são a mesma coisa.',
        isCorrect: false,
        explanation: 'Incorreto. Eles trabalham juntos, mas são completamente diferentes (corpo vs mente).',
      },
    ],
  },
  {
    id: 2,
    question: 'Qual peça é considerada o "CÉREBRO" do computador, responsável por fazer todos os cálculos e decisões?',
    illustration: '🧠⚡',
    category: 'hardware-software',
    options: [
      {
        text: 'Processador (CPU)',
        isCorrect: true,
        explanation: 'Exatamente! A CPU (Central Processing Unit) processa bilhões de ordens e cálculos a cada segundo.',
      },
      {
        text: 'Gabinete (Caixa de metal)',
        isCorrect: false,
        explanation: 'O gabinete é apenas a casa protetora externa das peças.',
      },
      {
        text: 'Teclado',
        isCorrect: false,
        explanation: 'O teclado é um periférico de entrada para você digitar.',
      },
    ],
  },
  {
    id: 3,
    question: 'O Mouse e o Teclado pertencem a qual tipo de periférico?',
    illustration: '⌨️🖱️',
    category: 'perifericos',
    options: [
      {
        text: 'Periféricos de ENTRADA (levam dados da sua mão PARA DENTRO do computador).',
        isCorrect: true,
        explanation: 'Muito bem! Quando você clica ou digita, a informação entra no computador.',
      },
      {
        text: 'Periféricos de SAÍDA (mostram o resultado para fora).',
        isCorrect: false,
        explanation: 'Periféricos de saída são o monitor e as caixas de som, que mostram coisas para você.',
      },
      {
        text: 'Não são periféricos, são softwares.',
        isCorrect: false,
        explanation: 'Eles são aparelhos físicos externos (hardware periférico).',
      },
    ],
  },
  {
    id: 4,
    question: 'O que o Monitor e as Caixas de Som fazem?',
    illustration: '🖥️🔊',
    category: 'perifericos',
    options: [
      {
        text: 'São periféricos de SAÍDA: entregam imagens e sons do computador para os nossos olhos e ouvidos.',
        isCorrect: true,
        explanation: 'Correto! Eles mostram para fora o resultado do processamento.',
      },
      {
        text: 'Servem apenas para desligar o computador.',
        isCorrect: false,
        explanation: 'Eles são responsáveis por toda a saída visual e auditiva do sistema.',
      },
      {
        text: 'São periféricos de entrada que gravam nossa voz.',
        isCorrect: false,
        explanation: 'Quem grava a voz é o microfone (entrada). A caixa de som emite o som (saída).',
      },
    ],
  },
  {
    id: 5,
    question: 'Antes de montar ou tocar nas peças de um computador, o que devemos fazer para evitar danos por eletricidade estática?',
    illustration: '⚡🖐️',
    category: 'montagem',
    options: [
      {
        text: 'Tocar em uma superfície de metal descarregada e trabalhar sobre mesa limpa sem tecidos/tapetes.',
        isCorrect: true,
        explanation: 'Excelente! Isso descarrega a estática do seu corpo e protege os circuitos delicados.',
      },
      {
        text: 'Montar as peças em cima da cama em cima de um cobertor de lã.',
        isCorrect: false,
        explanation: 'Nunca! Cobertores e tapetes acumulam muita eletricidade estática que pode queimar os chips.',
      },
      {
        text: 'Lamber os contatos dourados da memória.',
        isCorrect: false,
        explanation: 'Jamais! Isso oxidaria os contatos metálicos e estragaria a peça.',
      },
    ],
  },
  {
    id: 6,
    question: 'Onde o cabo do monitor (HDMI) deve ser conectado quando o computador possui uma Placa de Vídeo Dedicada?',
    illustration: '🔌📺',
    category: 'montagem',
    options: [
      {
        text: 'Diretamente nas saídas traseiras da Placa de Vídeo Dedicada (mais embaixo).',
        isCorrect: true,
        explanation: 'Perfeito! Se você ligar na placa-mãe, o monitor pode não dar sinal ou não usar o poder da placa.',
      },
      {
        text: 'Na tomada da parede direto.',
        isCorrect: false,
        explanation: 'O cabo de vídeo transmite sinal de imagem e deve ir na saída da placa de vídeo.',
      },
      {
        text: 'Na entrada do microfone.',
        isCorrect: false,
        explanation: 'A entrada de microfone é apenas para áudio P2/P3.',
      },
    ],
  },
];

export const ENHANCED_GLOSSARY_ITEMS: GlossaryItem[] = [
  // 1. CONCEITOS-CHAVE
  {
    id: 'hardware',
    term: 'Hardware',
    category: 'conceitos-chave',
    categoryLabel: 'Conceito Fundamental',
    emoji: '🛠️',
    pronunciation: 'Rárd-uer',
    simpleDefinition: 'A parte física e tangível do computador: todas as peças que você consegue pegar na mão, placas de circuito, cabos e parafusos.',
    everydayAnalogy: 'É como o Corpo Humano (os ossos, mãos, pernas e órgãos).',
    practicalExample: 'Teclado, mouse, tela, placas e fios.',
    badgeColor: 'bg-amber-100 text-amber-900 border-amber-300',
    borderColor: 'border-amber-300',
    bgColor: 'bg-amber-50/70',
  },
  {
    id: 'software',
    term: 'Software',
    category: 'conceitos-chave',
    categoryLabel: 'Conceito Fundamental',
    emoji: '💡',
    pronunciation: 'Sóf-tuer',
    simpleDefinition: 'A parte lógica e invisível: o conjunto de instruções, programas, aplicativos e jogos que dizem ao hardware o que fazer.',
    everydayAnalogy: 'É como a Mente e as Ideias (ou uma receita culinária que diz o que cozinhar).',
    practicalExample: 'WhatsApp, Windows, Word, navegadores de internet e joguinhos.',
    badgeColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    borderColor: 'border-emerald-300',
    bgColor: 'bg-emerald-50/70',
  },
  {
    id: 'peopleware',
    term: 'Peopleware',
    category: 'conceitos-chave',
    categoryLabel: 'Conceito Fundamental',
    emoji: '🧑‍💻',
    pronunciation: 'Pí-pol-uer',
    simpleDefinition: 'O elemento humano: as pessoas reais que usam, operam, programam, consertam ou administram os computadores.',
    everydayAnalogy: 'É o Motorista que dirige o carro ou o Cozinheiro que executa a receita.',
    practicalExample: 'Você lendo este guia, digitadores, programadores e técnicos.',
    badgeColor: 'bg-indigo-100 text-indigo-900 border-indigo-300',
    borderColor: 'border-indigo-300',
    bgColor: 'bg-indigo-50/70',
  },
  {
    id: 'perifericos',
    term: 'Periféricos',
    category: 'perifericos',
    categoryLabel: 'Aparelhos Conectados',
    emoji: '🔌',
    pronunciation: 'Pe-ri-fé-ri-cos',
    simpleDefinition: 'Aparelhos externos que ficam em volta da torre/máquina e servem para enviar dados para o computador (entrada) ou receber respostas (saída).',
    everydayAnalogy: 'Como seus Olhos, Ouvidos, Boca e Mãos que comunicam seu corpo com o mundo.',
    practicalExample: 'Mouse, teclado, fones de ouvido, monitores, webcams e impressoras.',
    badgeColor: 'bg-blue-100 text-blue-900 border-blue-300',
    borderColor: 'border-blue-300',
    bgColor: 'bg-blue-50/70',
  },

  // 2. PEÇAS INTERNAS
  {
    id: 'cpu',
    term: 'CPU (Processador)',
    acronymFull: 'Central Processing Unit (Unidade Central de Processamento)',
    category: 'pecas-internas',
    categoryLabel: 'Peça Interna',
    emoji: '🧠',
    pronunciation: 'Cê-Pê-U ou Pro-ces-sa-dor',
    simpleDefinition: 'O cérebro pensante do computador. É o chip mestre responsável por executar cálculos matemáticos e coordenar todas as ordens dos programas.',
    everydayAnalogy: 'O Cérebro da pessoa ou o Gerente Geral que toma todas as decisões rápidas.',
    practicalExample: 'Processadores Intel Core i3/i5/i7 e AMD Ryzen.',
    badgeColor: 'bg-blue-100 text-blue-900 border-blue-300',
    borderColor: 'border-blue-300',
    bgColor: 'bg-blue-50/70',
  },
  {
    id: 'ram',
    term: 'RAM (Memória RAM)',
    acronymFull: 'Random Access Memory (Memória de Acesso Aleatório)',
    category: 'pecas-internas',
    categoryLabel: 'Peça Interna',
    emoji: '📏',
    pronunciation: 'Me-mó-ria RÃN',
    simpleDefinition: 'A memória de trabalho ultrarrápida. Guarda apenas os dados dos programas que estão abertos agora. Quando desliga o computador, ela se apaga.',
    everydayAnalogy: 'A sua Mesa de Trabalho: quanto maior a mesa, mais cadernos e canetas você pode espalhar ao mesmo tempo sem bagunça.',
    practicalExample: 'Pentes de 8 GB ou 16 GB instalados na placa-mãe.',
    badgeColor: 'bg-purple-100 text-purple-900 border-purple-300',
    borderColor: 'border-purple-300',
    bgColor: 'bg-purple-50/70',
  },
  {
    id: 'ssd',
    term: 'SSD (Disco Sólido)',
    acronymFull: 'Solid State Drive (Unidade de Estado Sólido)',
    category: 'pecas-internas',
    categoryLabel: 'Peça Interna',
    emoji: '💾',
    pronunciation: 'Ésse-Ésse-Dê',
    simpleDefinition: 'Dispositivo moderno de armazenamento silencioso que guarda suas fotos, músicas, vídeos e o Windows para sempre, mesmo desligado. É 10x mais rápido que o antigo HD.',
    everydayAnalogy: 'Um Armário ou Gaveteiro de Arquivos seguro e instantâneo.',
    practicalExample: 'SSDs M.2 NVMe de 256 GB, 512 GB ou 1 TB.',
    badgeColor: 'bg-amber-100 text-amber-900 border-amber-300',
    borderColor: 'border-amber-300',
    bgColor: 'bg-amber-50/70',
  },
  {
    id: 'motherboard',
    term: 'Placa-Mãe',
    acronymFull: 'Motherboard / Mainboard',
    category: 'pecas-internas',
    categoryLabel: 'Peça Interna',
    emoji: '🏙️',
    pronunciation: 'Pla-ca-Mãe',
    simpleDefinition: 'A placa principal de circuito impresso onde todas as peças são conectadas e trocam informações elétricas em alta velocidade.',
    everydayAnalogy: 'A grande Cidade com ruas e avenidas por onde todos os cidadãos (peças) transitam.',
    practicalExample: 'Placas-mãe ASUS, Gigabyte, ASRock e MSI.',
    badgeColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    borderColor: 'border-emerald-300',
    bgColor: 'bg-emerald-50/70',
  },
  {
    id: 'gpu',
    term: 'GPU (Placa de Vídeo)',
    acronymFull: 'Graphics Processing Unit (Unidade de Processamento Gráfico)',
    category: 'pecas-internas',
    categoryLabel: 'Peça Interna',
    emoji: '🎨',
    pronunciation: 'Gê-Pê-U ou Placa de Vídeo',
    simpleDefinition: 'Chip ou placa dedicada a gerar e desenhar na tela todas as imagens, vídeos em alta resolução e gráficos tridimensionais de jogos.',
    everydayAnalogy: 'Os Olhos e o Artista que desenha o quadro com milhões de cores.',
    practicalExample: 'Placas Nvidia GeForce RTX e AMD Radeon.',
    badgeColor: 'bg-teal-100 text-teal-900 border-teal-300',
    borderColor: 'border-teal-300',
    bgColor: 'bg-teal-50/70',
  },
  {
    id: 'psu',
    term: 'Fonte de Alimentação',
    acronymFull: 'Power Supply Unit (Unidade de Fornecimento de Energia)',
    category: 'pecas-internas',
    categoryLabel: 'Peça Interna',
    emoji: '⚡',
    pronunciation: 'Fon-te de A-li-men-ta-ção',
    simpleDefinition: 'Recebe a eletricidade alternada da tomada de parede (110V/220V) e a transforma em correntes contínuas e seguras (12V, 5V, 3.3V) para os componentes.',
    everydayAnalogy: 'O Coração que bombeia sangue para todos os membros do corpo.',
    practicalExample: 'Fontes de 500W ou 650W com selo 80 Plus.',
    badgeColor: 'bg-rose-100 text-rose-900 border-rose-300',
    borderColor: 'border-rose-300',
    bgColor: 'bg-rose-50/70',
  },
  {
    id: 'cooler',
    term: 'Cooler e Ventoinhas',
    category: 'pecas-internas',
    categoryLabel: 'Peça Interna',
    emoji: '❄️',
    pronunciation: 'Cú-ler',
    simpleDefinition: 'Sistema de ventilação formado por bloco de metal e ventilador que retira o calor do processador para evitar que ele queime por superaquecimento.',
    everydayAnalogy: 'O Ar-condicionado ou o Suor que resfria a pele quando fazemos muito esforço.',
    practicalExample: 'Coolers a ar com ventoinha ou Water Coolers com líquido.',
    badgeColor: 'bg-cyan-100 text-cyan-900 border-cyan-300',
    borderColor: 'border-cyan-300',
    bgColor: 'bg-cyan-50/70',
  },
  {
    id: 'case',
    term: 'Gabinete (Chassi)',
    category: 'pecas-internas',
    categoryLabel: 'Peça Interna',
    emoji: '📦',
    pronunciation: 'Ga-bi-ne-te',
    simpleDefinition: 'A caixa de metal e vidro onde todas as peças internas ficam parafusadas, organizadas e protegidas contra poeira e impactos.',
    everydayAnalogy: 'A Casa e a Caixa Torácica protetora.',
    practicalExample: 'Gabinetes torre ATX e gabinetes compactos.',
    badgeColor: 'bg-slate-200 text-slate-900 border-slate-300',
    borderColor: 'border-slate-300',
    bgColor: 'bg-slate-50',
  },

  // 3. MEDIDAS E TECNOLOGIAS
  {
    id: 'usb',
    term: 'USB e USB-C',
    acronymFull: 'Universal Serial Bus (Barramento Serial Universal)',
    category: 'tecnologias',
    categoryLabel: 'Conexão Universal',
    emoji: '🔗',
    pronunciation: 'U-Ésse-Bê',
    simpleDefinition: 'Entrada padrão retangular ou oval onde você encaixa mouse, teclado, pendrive e cabos do celular para transferir dados e energia.',
    everydayAnalogy: 'A Tomada Universal onde quase tudo se conecta hoje.',
    practicalExample: 'Portas USB azuis (rápidas) e USB-C de celulares modernos.',
    badgeColor: 'bg-violet-100 text-violet-900 border-violet-300',
    borderColor: 'border-violet-300',
    bgColor: 'bg-violet-50/70',
  },
  {
    id: 'giga-tera',
    term: 'Gigabyte (GB) e Terabyte (TB)',
    category: 'tecnologias',
    categoryLabel: 'Unidade de Medida',
    emoji: '📊',
    pronunciation: 'Giga-baite e Tera-baite',
    simpleDefinition: 'Unidades de medida da capacidade de memória e armazenamento. 1 Terabyte (TB) equivale a 1.000 Gigabytes (GB).',
    everydayAnalogy: 'Como Litros de uma garrafa: quantos mais GB, mais fotos e filmes cabem dentro.',
    practicalExample: 'SSD de 512 GB guarda cerca de 100.000 fotos de celular!',
    badgeColor: 'bg-blue-100 text-blue-900 border-blue-300',
    borderColor: 'border-blue-300',
    bgColor: 'bg-blue-50/70',
  },
  {
    id: 'wifi-bluetooth',
    term: 'Wi-Fi e Bluetooth',
    category: 'tecnologias',
    categoryLabel: 'Conexões Sem Fio',
    emoji: '📡',
    pronunciation: 'Uai-Fai e Blu-túfi',
    simpleDefinition: 'Ondas de rádio invisíveis pelo ar: Wi-Fi conecta à internet de longa distância, e Bluetooth conecta fones e caixas de som bem pertinho sem fios.',
    everydayAnalogy: 'Conversar com alguém do outro lado da sala usando apenas a voz, sem precisar de barbante.',
    practicalExample: 'Internet da sua casa e fone de ouvido sem fio no celular.',
    badgeColor: 'bg-sky-100 text-sky-900 border-sky-300',
    borderColor: 'border-sky-300',
    bgColor: 'bg-sky-50/70',
  },
  {
    id: 'backup',
    term: 'Backup (Cópia de Segurança)',
    category: 'tecnologias',
    categoryLabel: 'Segurança',
    emoji: '🛡️',
    pronunciation: 'Béc-ap',
    simpleDefinition: 'Fazer uma segunda cópia das suas fotos e documentos importantes em outro lugar (como pendrive ou nuvem na internet) para nunca perder nada.',
    everydayAnalogy: 'Tirar uma cópia autenticada da sua certidão e guardar em gaveta separada.',
    practicalExample: 'Salvar fotos de família no Google Fotos ou pendrive.',
    badgeColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    borderColor: 'border-emerald-300',
    bgColor: 'bg-emerald-50/70',
  },
];

// Compatibility export
export const GLOSSARY_ITEMS = ENHANCED_GLOSSARY_ITEMS.map((item) => ({
  term: item.term,
  pronunciation: item.pronunciation,
  definition: item.simpleDefinition,
}));

